language: python
python:
- 3.6
sudo: required
services:
- docker
env:
  matrix:
  - ETCD_VERSION=v3.2.14
install:
- pip install -U tox tox-travis codecov
- curl -L https://github.com/coreos/etcd/releases/download/$ETCD_VERSION/etcd-$ETCD_VERSION-linux-amd64.tar.gz
  -o etcd-$ETCD_VERSION-linux-amd64.tar.gz
- tar xzvf etcd-$ETCD_VERSION-linux-amd64.tar.gz
- export PATH=$PATH:etcd-$ETCD_VERSION-linux-amd64
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  user: ramon.nb
  password:
    secure: n7SURGJ2syfXP4Sl6ilLdOgkC3SaeLOGQGau8GzUseDZVdgfMnvZbH7NkqxiTtypnt9p36pQRGbIsfzRI0xCcW2Id5jtRVKYUycsJFmeRESVZ4i35gUaCeiZ+djDvkXv+qealFeoTP4ihGS9HOLA5tqpKImAzk68VeobB0ywa3yZ40KFpYhQ2fAcR6PwjCNN7+N13DEx9ICwe9Y761hhJKTikX4bFVWwZw52DdKA+5trUarEHVxseKPCzCePxFQJ5yJWvlE+yAJwx0YizKcFAc9vSRWGCEn635wWlL7k5Al1zUrwDvBNsQN1StVy8/HYjT8qyC28SM4Pv4XSxWa1dYstNwoKi67/JP8aEChK1h8Lc+eD1y/RjZo8rt7zhzv6HZuhpjBxGr4gOjUqwRVkfAlc5NHhfFmEsDeRTzaOJ51lZPA6Pa1v+ZfiyqBqQ+VKgmwwG2dqq4YvRe/7Lt7jlrDg0zLkfEYMkHCPvuL3ff3mdggijDGgilzNs3XCUVdQLzXzz1iS2TIqUXVeYQi/e5aaFs9dxkDFa91i+YjQO5yqs2/nqIGCBSeAFw7i/Wr2iZP97HU5NgwOoV8RHbwPoP1B8bssL/KO5ukY+2uyHhYsy8VEN+rZsGnHeQhwwS3Gm2A9yhwq9GoXk4RbxyaE27QSj6sHK2H3IXJa/+gva80=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: onna/aiogrpc_etcd3
    condition: $TOXENV == py36